### ISSUE TITLE
Tiles 'pending' for a long time

### ISSUE THREAD

**Issue by brs-fcoo** [FCOO/ifm-maps#22]
Frequently (but inconsistently), some tiles are pending for a long time (10+ sek.)
Easiest to reproduce using the greenland map and zoomed to around zoomlevel 4.

So far only verified in Chrome.

**Comment by jblarsen** [comment]
We believe that this is an issue with the web server setup and not IFM Maps. We are working to fix the issue.

**Comment by jblarsen** [comment]
Has been fixed on ifm-beta.fcoo.dk
