### ISSUE TITLE
Coloured time bar missing in mobile view

### ISSUE THREAD

**Issue by brs-fcoo** [FCOO/ifm-maps#29]
The time bar showing when data is present (red/green) is missing from mobile view.

**Comment by NielsHolt** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gQdTQ76T&#x2F;334-css-til-malepunkter-vandstand-dk-og-tidevand-gl-med-variable-st-rrelse-a-la-msi"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> CSS til målepunkter (vandstand&#x2F;DK og Tidevand&#x2F;GL) med variable størrelse a la MSI</a>

**Comment by jblarsen** [comment]
Fixed
